#%RAML 1.0
---
title: API for Airport
version: v1
protocols: [ HTTPS ]

baseUri: https://{serverName}/{appName}-{version}
baseUriParameters:
  serverName:
    description: the name of the server
    example: api-dev.munich-airport.de
  appName:
    description: the name of the application
    example: aci-airport

securitySchemes:
  securedWithApiKey:   !include ../restBase/traits/securedWithApiKey.yaml

mediaType: application/json

types:
  Airport:             !include model/airport.full.schema.json
  AirportList:         !include model/airportList.schema.json
  AirportInfo:         !include model/airportInfo.schema.json
  AirportInfoList:     !include model/airportInfoList.schema.json
  ResponseMsg404:      !include ../restBase/model/responseMsg.schema.json

traits:
  TimestampQueryParam: !include ../restBase/traits/timestampQueryParam.yaml
  AcceptLang:          !include ../restBase/traits/acceptLanguageHeader.yaml
  UnknownKeyResponse:  !include ../restBase/traits/unknownKeyResponseWithMsg.yaml
  BadRequest:          !include ../restBase/traits/badRequestResponse.yaml

securedBy: [securedWithApiKey]

/airport/{airportId}/:
  is: [AcceptLang]
  description: GET returns detailed information about a specific airport
  uriParameters:
    airportId:
      description: The id of the airport
      type: integer
      required: true
  get:
    description: Returns detailed information about a specific airport
    responses:
      200:
        body:
          type: Airport
      404:
        description: The airport was not found

/airport/iata/{iataCode}/:
  is: [AcceptLang, UnknownKeyResponse: {typeName: ResponseMsg404}, BadRequest]
  description: GET returns detailed information of an active airport for the specified IATA code
  uriParameters:
    iataCode:
      description: The IATA code of the requested airport
      type: string
      minLength: 3
      maxLength: 3
  get:
    description: Returns detailed information of an active airport for the specified IATA code
    responses:
      200:
        body:
          type: Airport

/airport/icao/{icaoCode}/:
  is: [AcceptLang, UnknownKeyResponse: {typeName: ResponseMsg404}, BadRequest]
  description: GET returns detailed information of an active airport for the specified ICAO code
  uriParameters:
    icaoCode:
      description: The ICAO code of the requested airport
      type: string
      minLength: 4
      maxLength: 4
  get:
    description: Returns detailed information of an active airport for the specified ICAO code
    responses:
      200:
        body:
          type: Airport

/airports:
  is: [AcceptLang]
  description: GET returns all active airports
  get:
    description: Returns all active airports
    responses:
      200:
        body:
          type: AirportList
  /{airportCode}:
    is: [AcceptLang, UnknownKeyResponse: {typeName: ResponseMsg404}, BadRequest]
    uriParameters:
      airportCode:
        description: Code (IATA or ICAO) of the requested airport
        type: string
        minLength: 3
        maxLength: 4
    get:
      description: Returns a list of all active airports, which are connected with a direct flight (no transfer is needed).
      responses:
        200:
          body:
            type: AirportList


/airportInfo/{airportInfoId}:
  displayName: airportInfo
  is: [AcceptLang, UnknownKeyResponse: {typeName: ResponseMsg404}]
  description: GET returns specified airport's information
  uriParameters:
    airportInfoId:
      description: The id of the airport information
      type: integer
      required: true
  get:
    description: Returns specified airport's information
    responses:
      200:
        body:
          type: AirportInfo

/airportInfos/{airportId}:
  displayName: airportInfos
  is: [AcceptLang, UnknownKeyResponse: {typeName: ResponseMsg404}]
  description: GET returns all information about the specified airport
  uriParameters:
    airportId:
      description: The id of the airport
      type: integer
      required: true
  get:
    description: Returns all information about the specified airport
    responses:
      200:
        body:
          type: AirportInfoList
